<template>

<!-- TODO: Lang -->

<v-overlay v-model="isOpen" class="align-center justify-center">
    <v-card class="text-h5 pa-4">
        <v-card-text class="pa-0" >
            <v-table class="text-h6">
                <thead>
                    <tr class="text-h4">
                        <th class="text-left">Shortcut</th>
                        <th class="text-left">Action</th>
                    </tr>
                </thead>
                <tbody>
                <tr v-for="item,idx in KEYCODES" :key="idx">
                    <td class="keyboard-keys">
                        <span v-for="key,kIdx in item.keys" :key="kIdx">{{ key }}</span>
                    </td>
                    <td>
                        <p class="text-h5 mt-2">{{ item.title }}</p>
                        <br>
                        <p class="text-h6 mb-2">{{ item.desc }}</p>
                    </td>
                </tr>
                </tbody>
            </v-table>
        </v-card-text>
  </v-card>
</v-overlay>

</template>

<style lang="scss" scoped>

.keyboard-keys {

    span{
        background: rgb(60, 60, 60);
        border: 1px solid white;
        border-radius: .6rem;
        margin-right: .5rem;
        padding: 5px 10px;
        color: rgb(230, 230, 230);
    }
}

.v-card{
    max-width: 90vw;
}

</style>

<script lang="ts" setup>
import { Signals } from '@webapp/utils/signals/Signals';
import { useSignal } from '@webapp/utils/vue/VueSignalListener';
import { ref } from 'vue';

  const isOpen = ref(false);

  const KEYCODES = [
  {keys: ["CTRL","SHIFT","S"], title: "Save as ...", desc: "Saves the project in a new file."},
  {keys: ["CTRL","S"], title: "Save", desc: "Saves the project. If no file exists, a new one will be choosen by the user."},
  {keys: ["CTRL","O"], title: "Open", desc: "Open a project file."},
  {keys: ["CTRL","R"], title: "Reload Config", desc: "Reloads/Rebuilds the config which is used to display the preview or generate the code. Usually this is one automagically behind the scenes tho. Also config doesn't mean project settings. It means the actual config generated by the blocks you lay out in the workspace."},
  {keys: ["CTRL","SHIFT", "C"], title: "Copy Code", desc: "Copies the generated code into your clipboard."},
  {keys: ["CTRL","SHIFT", "V"], title: "Cycle View", desc: "Cycles through the views on the sidebar."},
  ];


  useSignal(Signals.OPEN_KEYBOARD_INFO, ()=>isOpen.value = true);

</script>